name: tool
publish_to: none
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  args: ^2.0.0
  charcode: ^1.2.0
  glob: ^2.1.0
  image: ^3.0.0
  markdown: ^5.0.0
  mime_type: ^1.0.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  sass: ^1.50.0
  shelf: ^1.0.0
  string_scanner: ^1.1.0
